
[cmake]
    min_ver = "3.12"

[project]
    name = "learn-asio"
    # The directory to store source of dependency.
    # Always relative to project root directory.
    deps_source_dir = "build/deps"
    # Where sub-build files of the dependency to store.
    deps_deploy_dir = "${CMAKE_BINARY_DIR}"
    cxx_standard = "14"

[precompiled_header]
    enabled = true
    # `pch_file` path is relative the current project directory.
    pch_file = "build/pch/precompile.h"

[platform_support]
    windows = true
    posix = true

[main_module]
    name = "timer"
    # choose between "library" or "executable"
    type = "executable"
    # effective only if precompiled_header is enable.
    use_pch = true
    # effective only if windows platform is enabled.
    use_msvc_static_analysis = true
